development: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  reconnect: true
  database: fpl_tactician_db
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock
  host: <%= ENV['DB_HOST'] || 'localhost' %>

test:
  <<: *default
  database: fpl_tactician_db_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'fpl_tactician_db' %>
  username: <%= ENV['DB_USERNAME'] || 'fpltactician'%>
  password: <%= ENV['DB_PASSWORD'] %>
  sslca: <%= ENV['DB_SSL_CA'] %>
  sslverify: <%= ENV['DB_SSL_VERIFY'] || 'false' %>
  host: <%= ENV['DB_HOST'] %>
